### ISSUE TITLE
Trace-Labs-OSINT-Search-Party-CTF-Contestant-Guide_v1.pdf contains incorrect credentials.

### ISSUE THREAD

**Issue by zer0uid** [tracelabs/tlosint-live#108]
**Bug Description**
Incorrect credentials contained in desktop PDF, needs updated to the current credentials used.

Trace-Labs-OSINT-Search-Party-CTF-Contestant-Guide_v1.pdf file on the desktop contains *old* credentials for the Trace Labs OSINT VM.  It instructs users to downlad the VM and log in with the username of kali, password kali.  This should be updated to reflect the credentials used in the current version of Trace Labs OSINT VM 2021.2, which are username osint, password osint.

**To Reproduce**
1. Open 'Trace-Labs-OSINT-Search-Party-CTF-Contestant-Guide_v1.pdf' on the desktop
2. Scroll down to 'Page 4'
4. See error: 
To log in use these default credentials: 
Username: Kali
Password: Kali

**Comment by 5nacks** [comment]
thanks for reporting this, we have now fixed it in https://download.tracelabs.org/Trace-Labs-OSINT-Search-Party-CTF-Contestant-Guide_v1.1.pdf :)
