### ISSUE TITLE
[Tool request] Skiptracer

### ISSUE THREAD

**Issue by l33tnull** [tracelabs/tlosint-live#145]
**Is your feature request related to a problem? Please describe.**
The ability to look up license plate information. 

**Describe the tool you'd like**
Skiptracer is an OSINT Python Web scraping Framework created by xillwillx.

**A link to the tool**
https://gitlab.com/illwill/skiptracer 

**Additional context**
![68747470733a2f2f692e696d6775722e636f6d2f6747304b5a30462e706e67](https://user-images.githubusercontent.com/58302571/171970048-3366a173-b950-48c5-95fc-4961a3a0f5e7.png)

**Comment by 5nacks** [comment]
Hey, this tool has been deprecated now. We did have it in the VM at one point.

**Comment by 5nacks** [comment]
Thanks for your suggestion
