### ISSUE TITLE
hi, can you add such modules to recon-ng https://github.com/Dec0ne/Recon-ng-Modules

### ISSUE THREAD

**Issue by 5nacks** [tracelabs/tlosint-live#21]
hi, can you add such modules to recon-ng https://github.com/Dec0ne/Recon-ng-Modules 

_Originally posted by @shanow7 in https://github.com/tracelabs/tlosint-live/issues/4#issuecomment-667968869_

**Comment by xFreed0m** [comment]
same as #45 & #32  - we will track individual tool request per issue for easier tracking and implementation.
