### ISSUE TITLE
Broken Desktop Icons

### ISSUE THREAD

**Issue by phunkpwnz** [tracelabs/tlosint-live#23]
Update the Desktop Icons to fix any broken links

**Comment by 5nacks** [comment]
I think you may have fixed this already @humandecoded ?

**Comment by humandecoded** [comment]
Hey @phunkpwnz, Which desktop icons? And which links where broken? Are you referring to the updater script?

**Comment by phunkpwnz** [comment]
This was from the meeting. And yes it was fixed.
