### ISSUE TITLE
[Packaging] PhoneInfoGA

### ISSUE THREAD

**Issue by 5nacks** [tracelabs/tlosint-live#26]
Facilitate packaging of PhoneInfoGA https://github.com/sundowndev/PhoneInfoga and update build script.

**Comment by xFreed0m** [comment]
Done - not by me, but seem to work:
![image](https://user-images.githubusercontent.com/13978578/96264253-aae7e000-0fcc-11eb-8c2e-a9c2fc5a1014.png)
