### ISSUE TITLE
Updater failing on some packages

### ISSUE THREAD

**Issue by scba21** [tracelabs/tlosint-live#39]
Updater is failing on DNS Dumpster (bad URL)

Updater is failing to compile sn0int due to failed checksum of rayon v1.4.0

**Comment by xFreed0m** [comment]
@scba21 can you please share screenshot\logs of the errors?

**Comment by scba21** [comment]
![image](https://user-images.githubusercontent.com/19156930/95664599-53460200-0afe-11eb-81c7-64bfb5740e58.png)

**Comment by scba21** [comment]
![image](https://user-images.githubusercontent.com/19156930/95664619-71136700-0afe-11eb-8ab1-27b5af6b6c12.png)

**Comment by xFreed0m** [comment]
the DNS Dumpster URL is incorrect, it should be https://github.com/PaulSec/API-dnsdumpster.com
Sn0int seems to be having permissions issues.

Which version of tlosing VM are you using, and what is the command you are using for update?

**Comment by scba21** [comment]
I'm using version 2 and the giant Updater button that appears on the home 
screen of the VM.

I agree with both of your conclusions and can work around them, but that 
defeats the purpose of the Updater button!

**Comment by xFreed0m** [comment]
found the issue, we had 2 new lines that broke the update for API-dnsdumpster.com
sn0int had wrong commands in the updater, also fixed.

Will be in effect on next version
