### ISSUE TITLE
Add more tools

### ISSUE THREAD

**Issue by shanow7** [tracelabs/tlosint-live#45]
Hi
Could you add this tools?
https://github.com/kennbroorg/iKy https://github.com/CiKu370/OSIF https://github.com/Cignoraptor-ita/cignotrack…… https://github.com/sc1341/InstagramOSINT…… https://github.com/SilverPoision/Rock-ON…… https://github.com/ultrasecurity/webkiller…… https://github.com/i3visio/osrframework……  https://github.com/VainlyStrain/Vaile…… https://github.com/saeeddhqan/Maryam…… https://github.com/0xInfection/TIDoS-Framework…… https://github.com/haroonawanofficial/ReconCobra…… https://github.com/leebaird/discover
https://doc.tafferugli.io/
Is it possible that tools could be proposed in a form like here https://www.youtube.com/watch?v=gt_g05y2uB0 ? (edited)

**Comment by xFreed0m** [comment]
Hi @shanow7 now we have issue template dedicated for tool adding.
I'll take a look at the links, but i think it will be easier and better to open a tool request per tool so it will be easier for us to track.
I'll be closing this one for now.
