### ISSUE TITLE
Investigate whether the update script can also update the distro

### ISSUE THREAD

**Issue by 5nacks** [tracelabs/tlosint-live#49]
**Is your feature request related to a problem? Please describe.**
We have no way to update the distribution after release except for Kali updates

**Describe the solution you'd like**
Have the updater script have this capability

**Describe alternatives you've considered**
We could also package up the updates in apt

**Additional context**
See whether the updates can come from github

**Comment by 5nacks** [comment]
@xFreed0m let me know if you can tackle this one :)

**Comment by xFreed0m** [comment]
I'll give it a go 💯

**Comment by xFreed0m** [comment]
Will be fixed on next dev merge, closing for now.
