### ISSUE TITLE
Add a VPN helper script and notification for VPN connect

### ISSUE THREAD

**Issue by 5nacks** [tracelabs/tlosint-live#50]
**Is your feature request related to a problem? Please describe.**
Make VPN access easier for non Linux users and potentially notification when VPN is active.

**Describe the solution you'd like**
A method to add VPN access to distro

**Describe alternatives you've considered**
Use the default method which is network manager

**Additional context**
enhance VPN support

**Comment by xFreed0m** [comment]
What exactly we want to add? OVPN support? Wireguard?
The notifications are built in into each product - we can have them installed, but each user would need to bring their own profiles\configuration in order to use them (which we can accommodate instructions for in the wiki)
