### ISSUE TITLE
Chromium missing from Kali

### ISSUE THREAD

**Issue by 5nacks** [tracelabs/tlosint-live#69]
**Describe the bug**
Build script is failing due to Chromium removal

**To Reproduce**
1. Run script

**Expected behavior**

Iso should build

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by jspinel** [comment]
Do you want to remove Chromium? Or add additional PPAs?

**Comment by 5nacks** [comment]
@jspinel looks like it's back so closing
