### ISSUE TITLE
[Tool request] Toutatis

### ISSUE THREAD

**Issue by richell82** [tracelabs/tlosint-live#92]
**Describe the tool you'd like**
Toutatis is a tool that can retrieve information such as phone number and email address (both public and obfuscated) from an instagram account

**A link to the tool**
https://github.com/megadose/toutatis

**Additional context**
This may be personal preference as i have not used many instagram tools, but i like the ability to see obfuscated email addresses and phone numbers. It is useful for cross referencing and potentially validating if the account belongs to the correct person.

**Comment by 5nacks** [comment]
Thanks will check it out!

**Comment by xFreed0m** [comment]
added in PR #97
